import type { HelpCenterData } from "@/lib/help-center/types";

export const HELP_CENTER_RU: HelpCenterData = {
  categories: [
    {
      id: "start",
      title: "Быстрый старт",
      description: "Вход, раскладка и базовые команды",
      guideIds: ["welcome", "windows", "omnibar"],
    },
    {
      id: "dashboard",
      title: "Дашборд",
      description: "Обзор и метрики",
      guideIds: ["dashboard-kpi"],
    },
    {
      id: "scanner",
      title: "AI-сканер",
      description: "Разбор документов и передача в ERP",
      guideIds: ["scanner-upload", "scanner-engines"],
    },
    {
      id: "crm",
      title: "Клиенты и CRM",
      description: "Контакты и проекты",
      guideIds: ["crm-clients"],
    },
    {
      id: "erp",
      title: "Документы и ERP",
      description: "Счета, архив и генерация",
      guideIds: ["erp-docs", "doc-creator"],
    },
    {
      id: "drive",
      title: "Google Drive",
      description: "Синхронизация, блокнот и разбор",
      guideIds: ["drive-sync"],
    },
    {
      id: "notebook",
      title: "NotebookLM",
      description: "Блокнот источников и чат",
      guideIds: ["notebook-sources"],
    },
    {
      id: "meckano",
      title: "Meckano",
      description: "Учёт времени и отчёты",
      guideIds: ["meckano-attendance"],
    },
    {
      id: "company-mgmt",
      title: "Управление компанией",
      description: "CRM, проекты, ERP и бизнес-сканирование",
      guideIds: [
        "company-mgmt-overview",
        "company-mgmt-crm",
        "company-mgmt-projects",
        "company-mgmt-erp",
        "company-mgmt-scan",
        "company-mgmt-profession",
      ],
    },
    {
      id: "settings",
      title: "Настройки и подписка",
      description: "Организация, биллинг и интеграции",
      guideIds: ["settings-org"],
    },
    {
      id: "troubleshoot",
      title: "Устранение неполадок",
      description: "Частые проблемы",
      guideIds: ["trouble-oauth", "trouble-scan"],
    },
  ],
  guides: [
    {
      id: "welcome",
      categoryId: "start",
      title: "Добро пожаловать в BSD-YBM OS",
      summary: "Обзор рабочего пространства: окна, Omnibar и AI.",
      readMinutes: 4,
      steps: [
        {
          title: "Вход",
          body: "Войдите через Google-аккаунт, одобренный для организации. После одобрения админом откроется полный доступ по тарифу.",
        },
        {
          title: "Главный экран",
          body: "После входа — рабочий стол с центральной областью (пустой или с окнами), боковой панелью приложений и командной строкой (Omnibar) внизу.",
        },
        {
          title: "Открыть приложение",
          body: "Нажмите иконку на панели (Дашборд, Клиенты, AI-сканер и т.д.) — каждое приложение в отдельном перетаскиваемом окне.",
        },
        {
          title: "Закрытие и фокус",
          body: "Закройте окно крестиком; клик по окну выводит его на передний план. Можно развернуть окно на весь рабочий стол.",
        },
        {
          title: "Сохранение раскладки",
          body: "Позиции окон сохраняются в браузере автоматически. Команда «очистить раскладку» сбрасывает все окна.",
        },
      ],
      tips: ["На мобильном используйте «Ещё» для доступа ко всем приложениям."],
      openWidget: "financeHub",
      openWidgetData: {"tab":"overview"},
    },
    {
      id: "windows",
      categoryId: "start",
      title: "Окна и раскладка",
      summary: "Работа с несколькими приложениями одновременно.",
      readMinutes: 3,
      steps: [
        { title: "Перетаскивание", body: "Тяните заголовок окна. Границы рабочей области не дают выйти за экран." },
        { title: "Размер", body: "Тяните углы окна для изменения размера." },
        { title: "Переключатель окон", body: "На мобильном: кнопка слоёв для переключения между открытыми окнами." },
        { title: "Чистый дашборд", body: "Команда «чистый дашборд» временно скрывает окна без удаления раскладки." },
      ],
      omnibarExamples: ["очистить раскладку", "показать окна", "чистый дашборд"],
    },
    {
      id: "omnibar",
      categoryId: "start",
      title: "Командная строка (Omnibar)",
      summary: "Поиск, текстовые команды и голосовой помощник.",
      readMinutes: 5,
      steps: [
        { title: "Ввод", body: "Введите текст в нижнюю строку и Enter — система понимает намерение (открыть экран, найти клиента и т.д.)." },
        { title: "Поиск", body: "Начните вводить имя клиента или проекта — появятся быстрые результаты." },
        { title: "Микрофон", body: "Нажмите иконку микрофона для Gemini Live; можно просить действия («открой сканер», «добавь задачу»)." },
        { title: "Статус", body: "Строка статуса над Omnibar показывает последнее действие или ошибку." },
      ],
      omnibarExamples: ["открыть клиентов", "сканировать счёт", "открыть блокнот", "добавить задачу в проект X"],
      openWidget: "aiHub",
      openWidgetData: {"tab":"chat"},
    },
    {
      id: "dashboard-kpi",
      categoryId: "dashboard",
      title: "Дашборд и KPI",
      summary: "Быстрый обзор активности организации.",
      readMinutes: 3,
      steps: [
        { title: "Открыть", body: "Нажмите иконку Дашборд на панели." },
        { title: "Метрики", body: "Активные проекты, клиенты и оборот — данные в реальном времени." },
        { title: "Недавняя активность", body: "Список последних документов со ссылкой в архив." },
        { title: "Быстрые действия", body: "Пустой экран предлагает карточки ярлыков к основным приложениям." },
      ],
      openWidget: "financeHub",
      openWidgetData: {"tab":"overview"},
    },
    {
      id: "scanner-upload",
      categoryId: "scanner",
      title: "Сканирование документа",
      summary: "Загрузка файла и структурированные данные.",
      readMinutes: 6,
      steps: [
        { title: "Открыть сканер", body: "Выберите «AI-сканер» на панели или команду «открыть сканер»." },
        { title: "Загрузка", body: "Перетащите файл или выберите — PDF, изображения и Office (до 25 МБ)." },
        { title: "Очередь", body: "Можно загрузить несколько файлов; для каждого показывается прогресс." },
        { title: "Результаты", body: "После сканирования: поставщик, сумма, дата и проект — можно править до подтверждения." },
        { title: "Подтвердить в ERP", body: "Подтвердите данные для сохранения расхода/документа в архив." },
        { title: "В блокнот", body: "«Сохранить в блокнот» создаёт источник NotebookLM из скана." },
      ],
      tips: ["Добавьте свои «инструкции сканирования» перед загрузкой."],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"scan"},
    },
    {
      id: "scanner-engines",
      categoryId: "scanner",
      title: "AI-движки при сканировании",
      summary: "Режим: Auto, Gemini, OpenAI или Document AI.",
      readMinutes: 4,
      steps: [
        { title: "Режим AUTO", body: "По умолчанию система выбирает движок по типу файла и балансу тарифа." },
        { title: "Балансы", body: "«Эконом» (Gemini) и «премиум» (OpenAI) списываются по настройкам организации." },
        { title: "Ошибки", body: "При сбое — проверьте формат, размер или попробуйте один движок." },
      ],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"scan"},
    },
    {
      id: "crm-clients",
      categoryId: "crm",
      title: "Управление клиентами",
      summary: "Таблица CRM, проекты и поиск.",
      readMinutes: 4,
      steps: [
        { title: "Открыть", body: "Иконка «Клиенты» открывает таблицу CRM." },
        { title: "Добавить", body: "Новый контакт: имя, телефон, налоговые данные." },
        { title: "Проекты", body: "«Доска проектов» — задачи и этапы, привязка к клиенту." },
        { title: "Семантический поиск", body: "В Omnibar ищите по имени — система предлагает совпадения." },
      ],
      omnibarExamples: ["найти клиента Коэн", "открыть доску проектов"],
      openWidget: "crmTable",
    },
    {
      id: "erp-docs",
      categoryId: "erp",
      title: "Архив ERP",
      summary: "Отсканированные документы, фильтры и экспорт.",
      readMinutes: 4,
      steps: [
        { title: "Архив", body: "«Архив ERP» собирает утверждённые файлы и сканы." },
        { title: "Фильтр", body: "По дате, клиенту или статусу оплаты." },
        { title: "Экспорт", body: "PDF или CSV для бухгалтерии по правам доступа." },
      ],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"archive"},
    },
    {
      id: "doc-creator",
      categoryId: "erp",
      title: "Генерация документов",
      summary: "Коммерческие предложения и счета.",
      readMinutes: 5,
      steps: [
        { title: "Генератор", body: "Откройте «Генератор документов» с панели." },
        { title: "Клиент", body: "Выберите из CRM или введите вручную." },
        { title: "Строки", body: "Позиции, цены и НДС — превью под тип бизнеса." },
        { title: "Создать", body: "Сформируйте PDF и отправьте клиенту или сохраните черновик." },
      ],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"create"},
    },
    {
      id: "drive-sync",
      categoryId: "drive",
      title: "Google Drive в организации",
      summary: "Папка BSD-YBM, синхронизация и действия с файлами.",
      readMinutes: 5,
      steps: [
        { title: "Подключение", body: "В настройках — переподключите Google с полными правами Drive." },
        { title: "Рабочая папка", body: "Система создаёт/использует папку BSD-YBM; имя можно изменить в настройках." },
        { title: "Синхронизация", body: "Авто каждые 90 секунд и кнопка ручного обновления." },
        { title: "В блокнот", body: "У файла/папки — иконка блокнота импортирует в NotebookLM." },
        { title: "AI-разбор", body: "Для одного файла — открывает сканер с файлом из Drive." },
      ],
      openWidget: "googleDrive",
    },
    {
      id: "notebook-sources",
      categoryId: "notebook",
      title: "NotebookLM — блокнот источников",
      summary: "Загрузка источников и чат с AI по ним.",
      readMinutes: 4,
      steps: [
        { title: "Открыть", body: "Иконка блокнота на панели." },
        { title: "Источники", body: "PDF, текст или импорт из скана/Drive." },
        { title: "Чат", body: "Задавайте вопросы — ответы только на основе источников." },
        { title: "Сохранение", body: "Блокноты сохраняются по пользователю/организации." },
      ],
      openWidget: "aiHub",
      openWidgetData: {"tab":"notebook"},
    },
    {
      id: "meckano-attendance",
      categoryId: "meckano",
      title: "Meckano — учёт времени",
      summary: "Вход/выход и отчёты (по тарифу).",
      readMinutes: 3,
      steps: [
        { title: "Доступ", body: "Meckano по тарифу организации или для авторизованного пользователя." },
        { title: "Отметки", body: "«вход Meckano» / «выход Meckano» в Omnibar или отчёты." },
        { title: "Отчёты", body: "Приложение «Отчёты Meckano» показывает данные посещаемости." },
      ],
      openWidget: "meckanoReports",
    },
    {
      id: "settings-org",
      categoryId: "settings",
      title: "Настройки организации",
      summary: "Логотип, профиль, Drive и пользователи.",
      readMinutes: 4,
      steps: [
        { title: "Открыть", body: "Иконка шестерёнки внизу панели." },
        { title: "Данные организации", body: "Название, ИНН, логотип и тип бизнеса." },
        { title: "Google Drive", body: "Папка синхронизации и переподключение." },
        { title: "Тариф", body: "Уровень подписки и баланс сканов (по правам)." },
      ],
      openWidget: "settings",
    },
    {
      id: "trouble-oauth",
      categoryId: "troubleshoot",
      title: "Проблемы входа Google",
      summary: "Нет refresh token или сбой Drive.",
      readMinutes: 3,
      steps: [
        { title: "Выход", body: "Выйдите и войдите снова." },
        { title: "Полное согласие", body: "В настройках «Переподключить Google» — одобрите все разрешения." },
        { title: "Браузер", body: "Попробуйте режим инкогнито или другой браузер при старых разрешениях." },
      ],
    },
    {
      id: "company-mgmt-overview",
      categoryId: "company-mgmt",
      title: "Режим управления компанией",
      summary: "Что включено по сравнению со строительством.",
      readMinutes: 3,
      steps: [
        { title: "Отличие", body: "Нет BOQ, Meckano и строительных меню — CRM, ERP, внутренние проекты и бизнес-сканирование." },
        { title: "Отрасль", body: "Админ выбирает «Управление компанией» и линию бизнеса в Настройки → Профессия." },
      ],
      openWidget: "settings",
    },
    {
      id: "company-mgmt-crm",
      categoryId: "company-mgmt",
      title: "CRM для бизнеса",
      summary: "Клиенты и задачи без строительной терминологии.",
      readMinutes: 4,
      steps: [
        { title: "CRM", body: "Откройте клиентов из лаунчера или Omnibar." },
        { title: "Проекты", body: "Внутренние проекты без BOQ." },
      ],
      openWidget: "crmTable",
    },
    {
      id: "company-mgmt-projects",
      categoryId: "company-mgmt",
      title: "Внутренние проекты",
      summary: "Gantt без BOQ.",
      readMinutes: 4,
      steps: [
        { title: "График", body: "Таймлайн проекта — зависимости без строк BOQ." },
        { title: "Документы", body: "Деловые документы проекта." },
      ],
      openWidget: "projectsHub",
      openWidgetData: {"tab":"project"},
    },
    {
      id: "company-mgmt-erp",
      categoryId: "company-mgmt",
      title: "ERP и документы",
      summary: "Выпуск, архив и биллинг.",
      readMinutes: 3,
      steps: [
        { title: "Архив", body: "Как в общем режиме." },
        { title: "Генератор", body: "Студия документов с бизнес-шаблонами." },
      ],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"archive"},
    },
    {
      id: "company-mgmt-scan",
      categoryId: "company-mgmt",
      title: "Бизнес-сканирование",
      summary: "Счета, предложения и офисные файлы.",
      readMinutes: 3,
      steps: [
        { title: "Режимы", body: "Бизнес-режимы сканера для вашей отрасли." },
        { title: "В ERP", body: "После подтверждения — в архив или выпуск." },
      ],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"scan"},
    },
    {
      id: "company-mgmt-profession",
      categoryId: "company-mgmt",
      title: "Профиль бизнеса",
      summary: "Смена отрасли и линии.",
      readMinutes: 2,
      steps: [
        { title: "Путь", body: "Настройки → Профессия или /app/settings/profession." },
        { title: "Сохранение", body: "Только админ; перелогин для обновления меню." },
      ],
      openWidget: "settings",
    },
    {
      id: "trouble-scan",
      categoryId: "troubleshoot",
      title: "Скан не удался",
      summary: "Что проверить, если разбор не работает.",
      readMinutes: 3,
      steps: [
        { title: "Размер и тип", body: "Макс. 25 МБ; PDF/изображение, не зашифрованный файл." },
        { title: "Баланс", body: "Проверьте остаток сканов по тарифу (настройки / админ)." },
        { title: "Движок", body: "Попробуйте один движок или более чёткие инструкции сканирования." },
      ],
      openWidget: "documentsHub",
      openWidgetData: {"tab":"scan"},
    },
  ],
  globalFaq: [
    {
      question: "Чем отличаются «Справка» и «AI-чат»?",
      answer:
        "Справка — центр помощи с руководствами и FAQ. AI-чат на главной панели — для свободных вопросов и умных действий.",
    },
    {
      question: "Как одобрить нового пользователя?",
      answer:
        "Админ платформы: «Управление» → вкладка регистраций → выбрать тариф и нажать Одобрить.",
    },
    {
      question: "Сохраняется ли раскладка между устройствами?",
      answer: "Раскладка хранится в localStorage браузера только на текущем устройстве.",
    },
    {
      question: "Как добавить файл из Google Drive в блокнот?",
      answer: "В виджете Drive нажмите иконку блокнота у файла или папки.",
    },
    {
      question: "Что делает Gemini Live?",
      answer:
        "Голосовой чат с помощником: открытие экранов, сканирование, задачи и т.д. — по правам тарифа.",
    },
    {
      question: "Кому видна кнопка «Управление»?",
      answer: "Только SUPER_ADMIN платформы — обычно владелец аккаунта BSD-YBM.",
    },
  ],
};
