import type { HelpCenterData } from "@/lib/help-center/types";

export const HELP_CENTER_EN: HelpCenterData = {
  categories: [
    {
      id: "start",
      title: "Quick start",
      description: "Sign-in, layout, and basic commands",
      guideIds: ["welcome", "windows", "omnibar"],
    },
    {
      id: "dashboard",
      title: "Dashboard",
      description: "Overview and metrics",
      guideIds: ["dashboard-kpi"],
    },
    {
      id: "scanner",
      title: "AI Scanner",
      description: "Document parsing and ERP handoff",
      guideIds: ["scanner-upload", "scanner-engines"],
    },
    {
      id: "crm",
      title: "Clients & CRM",
      description: "Contacts and projects",
      guideIds: ["crm-clients"],
    },
    {
      id: "erp",
      title: "Documents & ERP",
      description: "Invoices, archive, and generation",
      guideIds: ["erp-docs", "doc-creator"],
    },
    {
      id: "drive",
      title: "Google Drive",
      description: "Sync, notebook, and parsing",
      guideIds: ["drive-sync"],
    },
    {
      id: "notebook",
      title: "NotebookLM",
      description: "Source notebook and chat",
      guideIds: ["notebook-sources"],
    },
    {
      id: "meckano",
      title: "Meckano",
      description: "Attendance and reports",
      guideIds: ["meckano-attendance"],
    },
    {
      id: "company-mgmt",
      title: "Company management",
      description: "CRM, projects, ERP and business scanning",
      guideIds: [
        "company-mgmt-overview",
        "company-mgmt-crm",
        "company-mgmt-projects",
        "company-mgmt-erp",
        "company-mgmt-scan",
        "company-mgmt-profession",
      ],
    },
    {
      id: "settings",
      title: "Settings & billing",
      description: "Organization, billing, and integrations",
      guideIds: ["settings-org"],
    },
    {
      id: "troubleshoot",
      title: "Troubleshooting",
      description: "Common issues",
      guideIds: ["trouble-oauth", "trouble-scan"],
    },
  ],
  guides: [
    {
      id: "welcome",
      categoryId: "start",
      title: "Welcome to BSD-YBM OS",
      summary: "Overview of the workspace: floating windows, Omnibar, and AI.",
      readMinutes: 4,
      steps: [
        {
          title: "Sign in",
          body: "Sign in with a Google account approved for your organization. After admin approval you get full access based on your plan.",
        },
        {
          title: "Home screen",
          body: "After sign-in you see a desktop with a central area (empty or with open windows), an app sidebar, and the command bar (Omnibar) at the bottom.",
        },
        {
          title: "Open an app",
          body: "Click an icon in the sidebar (Dashboard, Clients, AI Scanner, etc.) — each app opens in its own draggable, resizable window.",
        },
        {
          title: "Close and focus",
          body: "Close a window with X; clicking a window brings it to the front. You can maximize a window within the workspace.",
        },
        {
          title: "Layout persistence",
          body: "Window positions are saved automatically in the browser. The “clear layout” command resets all windows.",
        },
      ],
      tips: ["On mobile, use the “More” button to reach all apps."],
      openWidget: "dashboard",
    },
    {
      id: "windows",
      categoryId: "start",
      title: "Windows and layout",
      summary: "Working with multiple apps at once.",
      readMinutes: 3,
      steps: [
        { title: "Drag", body: "Drag the window title bar to move. Workspace bounds keep windows on screen." },
        { title: "Resize", body: "Drag window corners to enlarge or shrink." },
        { title: "Window switcher", body: "On mobile: use the layers button to switch between open windows." },
        { title: "Clean dashboard", body: "The “clean dashboard” command temporarily hides windows without deleting the layout." },
      ],
      omnibarExamples: ["clear layout", "show windows", "clean dashboard"],
    },
    {
      id: "omnibar",
      categoryId: "start",
      title: "Command bar (Omnibar)",
      summary: "Search, text commands, and voice assistant.",
      readMinutes: 5,
      steps: [
        { title: "Typing", body: "Type in the bottom bar and press Enter — the system interprets intent (open screen, find client, etc.)." },
        { title: "Search", body: "Start typing a client or project name — quick results appear for selection." },
        { title: "Microphone", body: "Click the mic icon for Gemini Live; you can ask for actions (“open scanner”, “add task”)." },
        { title: "Status", body: "The status line above the Omnibar shows the last action or an error." },
      ],
      omnibarExamples: ["open clients", "scan invoice", "open notebook", "add task to project X"],
      openWidget: "aiChatFull",
    },
    {
      id: "dashboard-kpi",
      categoryId: "dashboard",
      title: "Dashboard and KPIs",
      summary: "Quick view of organization activity.",
      readMinutes: 3,
      steps: [
        { title: "Open", body: "Click the Dashboard icon in the sidebar." },
        { title: "Metrics", body: "See active projects, clients, and billing turnover — data is loaded in real time." },
        { title: "Recent activity", body: "List of recent documents with a quick link to the archive." },
        { title: "Quick actions", body: "The empty state offers shortcut cards to main apps." },
      ],
      openWidget: "dashboard",
    },
    {
      id: "scanner-upload",
      categoryId: "scanner",
      title: "Scan a document",
      summary: "Upload a file and get structured data.",
      readMinutes: 6,
      steps: [
        { title: "Open scanner", body: "Choose “AI Scanner” in the sidebar or run “open scanner”." },
        { title: "Upload", body: "Drag a file to the upload area or click to browse — PDF, images, and Office are supported (up to 25MB)." },
        { title: "Scan queue", body: "You can upload multiple files; each is processed with progress shown." },
        { title: "Results", body: "After scanning: vendor, amount, date, and project suggestion — edit before confirming." },
        { title: "Confirm to ERP", body: "Confirm data to save expense/document to the archive." },
        { title: "Save to notebook", body: "“Save to notebook” creates a NotebookLM source from the scan." },
      ],
      tips: ["Add custom “scan instructions” before uploading."],
      openWidget: "aiScanner",
    },
    {
      id: "scanner-engines",
      categoryId: "scanner",
      title: "AI engines in scanning",
      summary: "Run mode: Auto, Gemini, OpenAI, or Document AI.",
      readMinutes: 4,
      steps: [
        { title: "AUTO mode", body: "Default — the system picks an engine by file type and plan balance." },
        { title: "Balances", body: "“Economy” (Gemini) and “premium” (OpenAI) scans are deducted per organization settings." },
        { title: "Errors", body: "If a scan fails — check format, size, or try a single-engine mode." },
      ],
      openWidget: "aiScanner",
    },
    {
      id: "crm-clients",
      categoryId: "crm",
      title: "Client management",
      summary: "CRM table, projects, and search.",
      readMinutes: 4,
      steps: [
        { title: "Open", body: "The “Clients” icon in the sidebar opens the CRM table." },
        { title: "Add", body: "Add a new contact with name, phone, and tax details." },
        { title: "Projects", body: "“Project board” shows tasks and stages — link to a client." },
        { title: "Semantic search", body: "In the Omnibar search by name; the system suggests matches." },
      ],
      omnibarExamples: ["find client Cohen", "open project board"],
      openWidget: "crmTable",
    },
    {
      id: "erp-docs",
      categoryId: "erp",
      title: "ERP archive",
      summary: "Scanned documents, filters, and export.",
      readMinutes: 4,
      steps: [
        { title: "Archive", body: "“ERP Archive” centralizes approved files and scans." },
        { title: "Filter", body: "Filter by date, client, or payment status." },
        { title: "Export", body: "Export PDF or CSV for accounting per permissions." },
      ],
      openWidget: "erpArchive",
    },
    {
      id: "doc-creator",
      categoryId: "erp",
      title: "Document generation",
      summary: "Quotes and invoices.",
      readMinutes: 5,
      steps: [
        { title: "Document creator", body: "Open “Document creator” from the sidebar." },
        { title: "Choose client", body: "Pick a client from CRM or enter manually." },
        { title: "Line items", body: "Add items, prices, and VAT — preview matches business type." },
        { title: "Generate", body: "Generate PDF and send to client or save as draft." },
      ],
      openWidget: "docCreator",
    },
    {
      id: "drive-sync",
      categoryId: "drive",
      title: "Google Drive in your org",
      summary: "BSD-YBM folder, sync, and file actions.",
      readMinutes: 5,
      steps: [
        { title: "Connect", body: "In Settings — reconnect Google with full Drive permissions." },
        { title: "Work folder", body: "The system creates/uses a BSD-YBM folder; you can rename it in settings." },
        { title: "Sync", body: "Auto sync every 90 seconds plus a manual refresh button." },
        { title: "Add to notebook", body: "On any file/folder row — notebook icon imports content to NotebookLM." },
        { title: "AI parse", body: "On a single file — opens the scanner with that Drive file." },
      ],
      openWidget: "googleDrive",
    },
    {
      id: "notebook-sources",
      categoryId: "notebook",
      title: "NotebookLM — source notebook",
      summary: "Upload sources and chat with AI on them.",
      readMinutes: 4,
      steps: [
        { title: "Open", body: "Notebook icon in the sidebar." },
        { title: "Sources", body: "Add PDF, text, or import from scan/Drive." },
        { title: "Chat", body: "Ask questions — answers are grounded in sources only." },
        { title: "Save", body: "Notebooks are saved per user/organization." },
      ],
      openWidget: "notebookLM",
    },
    {
      id: "meckano-attendance",
      categoryId: "meckano",
      title: "Meckano — attendance",
      summary: "Clock in/out and reports (authorized plans).",
      readMinutes: 3,
      steps: [
        { title: "Access", body: "Meckano access depends on org plan or authorized user." },
        { title: "Report", body: "“clock in Meckano” / “clock out Meckano” in Omnibar or dedicated reports." },
        { title: "Reports", body: "“Meckano Reports” app shows attendance data." },
      ],
      openWidget: "meckanoReports",
    },
    {
      id: "settings-org",
      categoryId: "settings",
      title: "Organization settings",
      summary: "Logo, profession, Drive, and user assignment.",
      readMinutes: 4,
      steps: [
        { title: "Open", body: "Gear icon at the bottom of the sidebar." },
        { title: "Org details", body: "Update name, company ID, logo, and business type." },
        { title: "Google Drive", body: "Set sync folder and reconnect." },
        { title: "Plan", body: "View plan tier and scan balances (if permitted)." },
      ],
      openWidget: "settings",
    },
    {
      id: "trouble-oauth",
      categoryId: "troubleshoot",
      title: "Google sign-in issues",
      summary: "Missing refresh token or Drive connection failed.",
      readMinutes: 3,
      steps: [
        { title: "Sign out", body: "Sign out and sign in again." },
        { title: "Full consent", body: "In Settings click “Reconnect Google” — approve all permissions." },
        { title: "Browser", body: "Try a private window or another browser if old permissions are cached." },
      ],
    },
    {
      id: "company-mgmt-overview",
      categoryId: "company-mgmt",
      title: "Company management mode",
      summary: "What is enabled vs construction mode.",
      readMinutes: 3,
      steps: [
        { title: "Main difference", body: "No BOQ, Meckano or construction menus — CRM, ERP, internal projects and business scanning." },
        { title: "Industry", body: "Org admin sets Company management and a business line under Settings → Profession." },
      ],
      openWidget: "settings",
    },
    {
      id: "company-mgmt-crm",
      categoryId: "company-mgmt",
      title: "CRM for business",
      summary: "Clients and tasks without construction field terms.",
      readMinutes: 4,
      steps: [
        { title: "Open CRM", body: "Launch Clients from the launcher or Omnibar." },
        { title: "Projects", body: "Link internal projects to clients — no BOQ." },
      ],
      openWidget: "crm",
    },
    {
      id: "company-mgmt-projects",
      categoryId: "company-mgmt",
      title: "Internal projects",
      summary: "Gantt and tasks without BOQ.",
      readMinutes: 4,
      steps: [
        { title: "Timeline", body: "Open the project timeline — dependencies without BOQ rows." },
        { title: "Documents", body: "Business-oriented project documents only." },
      ],
      openWidget: "project",
    },
    {
      id: "company-mgmt-erp",
      categoryId: "company-mgmt",
      title: "ERP & documents",
      summary: "Issuing, archive and billing.",
      readMinutes: 3,
      steps: [
        { title: "Archive", body: "Issued and draft documents like the general path." },
        { title: "Creator", body: "Document studio supports business templates." },
      ],
      openWidget: "erp",
    },
    {
      id: "company-mgmt-scan",
      categoryId: "company-mgmt",
      title: "Business scanning",
      summary: "Invoices, quotes and office documents.",
      readMinutes: 3,
      steps: [
        { title: "Scan modes", body: "Scanner offers business modes (not site/blueprint) for your industry." },
        { title: "To ERP", body: "After approval — save to archive or issue a document." },
      ],
      openWidget: "aiScanner",
    },
    {
      id: "company-mgmt-profession",
      categoryId: "company-mgmt",
      title: "Business profile",
      summary: "Change industry and business line.",
      readMinutes: 2,
      steps: [
        { title: "Path", body: "Settings → Profession, or /app/settings/profession in the workspace." },
        { title: "Save", body: "Org admin only; sign out and back in to refresh menus." },
      ],
      openWidget: "settings",
    },
    {
      id: "trouble-scan",
      categoryId: "troubleshoot",
      title: "Scan failed",
      summary: "What to check when parsing does not work.",
      readMinutes: 3,
      steps: [
        { title: "Size and type", body: "Max 25MB; ensure PDF/image, not encrypted." },
        { title: "Balance", body: "Check remaining scans on the plan (Settings / admin)." },
        { title: "Engine", body: "Try a single-engine mode or clearer scan instructions." },
      ],
      openWidget: "aiScanner",
    },
  ],
  globalFaq: [
    {
      question: "What is the difference between Help and AI Chat?",
      answer:
        "Help opens the help center — guides and FAQ. AI Chat in the main sidebar is for free-form questions and smart actions.",
    },
    {
      question: "How do I approve a new user?",
      answer:
        "Platform admin opens “Admin” → Registrations tab → selects a plan and clicks Approve.",
    },
    {
      question: "Is layout saved across devices?",
      answer: "Layout is stored in the browser’s localStorage on the current device only.",
    },
    {
      question: "How do I add a Google Drive file to the notebook?",
      answer: "In the Drive widget click the notebook icon next to the file or folder.",
    },
    {
      question: "What does Gemini Live do?",
      answer:
        "Enables voice chat with the assistant; you can request opening screens, scanning, tasks, etc. — per plan permissions.",
    },
    {
      question: "Who sees the “Admin” button?",
      answer: "Only platform admin (SUPER_ADMIN) — usually the BSD-YBM account owner.",
    },
  ],
};
