import type { HelpCenterData } from "@/lib/help-center/types";

export const HELP_CENTER_HE: HelpCenterData = {
  categories: [
    {
      id: "start",
      title: "התחלה מהירה",
      description: "כניסה, פריסה ופקודות בסיס",
      guideIds: ["welcome", "windows", "omnibar"],
    },
    {
      id: "dashboard",
      title: "דאשבורד",
      description: "סקירה ומדדים",
      guideIds: ["dashboard-kpi"],
    },
    {
      id: "scanner",
      title: "סורק AI",
      description: "פענוח מסמכים והעברה ל-ERP",
      guideIds: ["scanner-upload", "scanner-engines"],
    },
    {
      id: "crm",
      title: "לקוחות ו-CRM",
      description: "אנשי קשר ופרויקטים",
      guideIds: ["crm-clients"],
    },
    {
      id: "erp",
      title: "מסמכים ו-ERP",
      description: "חשבוניות, ארכיון והפקה",
      guideIds: ["erp-docs", "doc-creator"],
    },
    {
      id: "drive",
      title: "Google Drive",
      description: "סנכרון, מחברת ופענוח",
      guideIds: ["drive-sync"],
    },
    {
      id: "notebook",
      title: "NotebookLM",
      description: "מחברת מקורות ושיחה",
      guideIds: ["notebook-sources"],
    },
    {
      id: "meckano",
      title: "מקאנו",
      description: "נוכחות ודוחות",
      guideIds: ["meckano-attendance"],
    },
    {
      id: "settings",
      title: "הגדרות ומנוי",
      description: "ארגון, חיוב ואינטגרציות",
      guideIds: ["settings-org"],
    },
    {
      id: "troubleshoot",
      title: "פתרון תקלות",
      description: "בעיות נפוצות",
      guideIds: ["trouble-oauth", "trouble-scan"],
    },
  ],
  guides: [
    {
      id: "welcome",
      categoryId: "start",
      title: "ברוכים הבאים ל-BSD-YBM OS",
      summary: "מבט על מרחב העבודה והרעיון המרכזי: חלונות צפים, Omnibar ו-AI.",
      readMinutes: 4,
      steps: [
        {
          title: "התחברות",
          body: "היכנסו עם חשבון Google שאושר לארגון. לאחר אישור מנהל המערכת תקבלו גישה מלאה לפי רמת המנוי.",
        },
        {
          title: "מסך הבית",
          body: "לאחר הכניסה תראו שולחן עבודה עם אזור מרכזי ריק או חלונות פתוחים, סרגל יישומים בצד ושורת פקודה (Omnibar) למטה.",
        },
        {
          title: "פתיחת יישום",
          body: "לחצו על אייקון בסרגל (דאשבורד, לקוחות, סורק AI וכו') — כל יישום נפתח בחלון נפרד שניתן לגרור ולשנות גודל.",
        },
        {
          title: "סגירה ומיקוד",
          body: "סגרו חלון ב-X; לחיצה על חלון מביאה אותו לחזית. ניתן למקסם חלון לגודל מלא בתוך אזור העבודה.",
        },
        {
          title: "שמירת פריסה",
          body: "מיקום החלונות נשמר אוטומטית בדפדפן. פקודה \"נקה פריסה\" מאפסת את כל החלונות.",
        },
      ],
      tips: ["השתמשו בכפתור «עוד» במובייל לגישה לכל היישומים."],
      openWidget: "dashboard",
    },
    {
      id: "windows",
      categoryId: "start",
      title: "ניהול חלונות ופריסה",
      summary: "איך לעבוד עם מספר יישומים במקביל.",
      readMinutes: 3,
      steps: [
        { title: "גרירה", body: "גררו את כותרת החלון כדי להזיז. גבולות אזור העבודה מונעים יציאה מהמסך." },
        { title: "שינוי גודל", body: "משכו מפינות החלון להגדלה או הקטנה." },
        { title: "מחליף חלונות", body: "במובייל: כפתור שכבות לעבור בין חלונות פתוחים." },
        { title: "דשבורד נקי", body: "פקודת «דשבורד נקי» מסתירה חלונות זמנית ללא מחיקת פריסה." },
      ],
      omnibarExamples: ["נקה פריסה", "הצג חלונות", "דשבורד נקי"],
    },
    {
      id: "omnibar",
      categoryId: "start",
      title: "שורת הפקודה (Omnibar)",
      summary: "חיפוש, פקודות טקסט ועוזר קולי.",
      readMinutes: 5,
      steps: [
        { title: "הקלדה", body: "הקלידו בשורה התחתונה ולחצו Enter — המערכת מפרשת כוונה (פתיחת מסך, חיפוש לקוח וכו')." },
        { title: "חיפוש", body: "התחילו להקליד שם לקוח או פרויקט — יוצגו תוצאות לבחירה מהירה." },
        { title: "מיקרופון", body: "לחצו על אייקון המיקרופון לשיחה עם Gemini Live; ניתן לבקש פעולות («פתח סורק», «הוסף משימה»)." },
        { title: "סטטוס", body: "שורת הסטטוס מעל ה-Omnibar מציגה פעולה אחרונה או שגיאה." },
      ],
      omnibarExamples: ["פתח לקוחות", "סרוק חשבונית", "פתח מחברת", "הוסף משימה לפרויקט X"],
      openWidget: "aiChatFull",
    },
    {
      id: "dashboard-kpi",
      categoryId: "dashboard",
      title: "דאשבורד ומדדים",
      summary: "סקירה מהירה של פעילות הארגון.",
      readMinutes: 3,
      steps: [
        { title: "פתיחה", body: "לחצו על אייקון הדאשבורד בסרגל." },
        { title: "מדדים", body: "צפו בפרויקטים פעילים, לקוחות ומחזור חיוב — הנתונים נשאבים מהמערכת בזמן אמת." },
        { title: "פעילות אחרונה", body: "רשימת מסמכים אחרונים עם קישור מהיר לארכיון." },
        { title: "פעולות מהירות", body: "מסך ריק מציע כרטיסי קיצור ליישומים מרכזיים." },
      ],
      openWidget: "dashboard",
    },
    {
      id: "scanner-upload",
      categoryId: "scanner",
      title: "סריקת מסמך",
      summary: "העלאת קובץ וקבלת נתונים מובנים.",
      readMinutes: 6,
      steps: [
        { title: "פתיחת הסורק", body: "בחרו «סורק AI» בסרגל או פקודה «פתח סורק»." },
        { title: "העלאה", body: "גררו קובץ לאזור ההעלאה או לחצו לבחירה — PDF, תמונות ו-Office נתמכים (עד 25MB)." },
        { title: "תור סריקה", body: "ניתן להעלות מספר קבצים; כל קובץ עובר בעיבוד עם התקדמות." },
        { title: "תוצאות", body: "לאחר הסריקה: ספק, סכום, תאריך והמלצת פרויקט — ניתן לערוך לפני אישור." },
        { title: "אישור ל-ERP", body: "אשרו את הנתונים כדי לשמור הוצאה/מסמך בארכיון." },
        { title: "שמירה למחברת", body: "כפתור שמירה למחברת יוצר מקור מסריקה ב-NotebookLM." },
      ],
      tips: ["הוסיפו «הנחיות סריקה» מותאמות אישית לפני ההעלאה."],
      openWidget: "aiScanner",
    },
    {
      id: "scanner-engines",
      categoryId: "scanner",
      title: "מנועי AI בסריקה",
      summary: "בחירת מצב ריצה: אוטומטי, Gemini, OpenAI או Document AI.",
      readMinutes: 4,
      steps: [
        { title: "מצב AUTO", body: "ברירת מחדל — המערכת בוחרת מנוע לפי סוג הקובץ ויתרות המנוי." },
        { title: "יתרות", body: "סריקות «זולות» (Gemini) ו«פרימיום» (OpenAI) מנוכות לפי הגדרות הארגון." },
        { title: "שגיאות", body: "אם סריקה נכשלה — בדקו פורמט, גודל, או נסו מצב מנוע יחיד." },
      ],
      openWidget: "aiScanner",
    },
    {
      id: "crm-clients",
      categoryId: "crm",
      title: "ניהול לקוחות",
      summary: "טבלת CRM, פרויקטים וחיפוש.",
      readMinutes: 4,
      steps: [
        { title: "פתיחה", body: "אייקון «לקוחות» בסרגל פותח את טבלת ה-CRM." },
        { title: "הוספה", body: "הוסיפו איש קשר חדש עם שם, טלפון ופרטי מס." },
        { title: "פרויקטים", body: "«לוח פרויקטים» מציג משימות ושלבים — ניתן לשייך ללקוח." },
        { title: "חיפוש סמנטי", body: "ב-Omnibar חפשו לפי שם; המערכת מציעה התאמות." },
      ],
      omnibarExamples: ["חפש לקוח כהן", "פתח לוח פרויקטים"],
      openWidget: "crmTable",
    },
    {
      id: "erp-docs",
      categoryId: "erp",
      title: "ארכיון ERP",
      summary: "מסמכים מסורקים, סינון וייצוא.",
      readMinutes: 4,
      steps: [
        { title: "ארכיון", body: "«ארכיון ERP» מרכז קבצים וסריקות שאושרו." },
        { title: "סינון", body: "סננו לפי תאריך, לקוח או סטטוס תשלום." },
        { title: "ייצוא", body: "ייצוא PDF או CSV לרואה חשבון לפי הרשאות." },
      ],
      openWidget: "erpArchive",
    },
    {
      id: "doc-creator",
      categoryId: "erp",
      title: "הפקת מסמכים",
      summary: "הצעות מחיר וחשבוניות.",
      readMinutes: 5,
      steps: [
        { title: "מחולל מסמכים", body: "פתחו «הפקת מסמכים» מהסרגל." },
        { title: "בחירת לקוח", body: "בחרו לקוח מה-CRM או הזינו ידנית." },
        { title: "שורות", body: "הוסיפו פריטים, מחירים ומע\"מ — התצוגה מותאמת לסוג העסק." },
        { title: "הפקה", body: "הפיקו PDF ושלחו ללקוח או שמרו כטיוטה." },
      ],
      openWidget: "docCreator",
    },
    {
      id: "drive-sync",
      categoryId: "drive",
      title: "Google Drive בארגון",
      summary: "תיקיית BSD-YBM, סנכרון ופעולות על קבצים.",
      readMinutes: 5,
      steps: [
        { title: "חיבור", body: "בהגדרות — חיבור מחדש ל-Google עם הרשאות Drive מלאות." },
        { title: "תיקיית עבודה", body: "המערכת יוצרת/משתמשת בתיקיית BSD-YBM; ניתן לשנות שם בהגדרות." },
        { title: "סנכרון", body: "סנכרון אוטומטי כל 90 שניות + כפתור רענון ידני." },
        { title: "הוספה למחברת", body: "בכל שורת קובץ/תיקייה — אייקון מחברת מייבא תוכן ל-NotebookLM." },
        { title: "פענוח AI", body: "על קובץ בודד — פותח את הסורק עם הקובץ מה-Drive." },
      ],
      openWidget: "googleDrive",
    },
    {
      id: "notebook-sources",
      categoryId: "notebook",
      title: "NotebookLM — מחברת מקורות",
      summary: "העלאת מקורות ושיחה עם AI עליהם.",
      readMinutes: 4,
      steps: [
        { title: "פתיחה", body: "אייקון המחברת בסרגל." },
        { title: "מקורות", body: "הוסיפו PDF, טקסט או ייבוא מסריקה/Drive." },
        { title: "שיחה", body: "שאלו שאלות — התשובות מבוססות על המקורות בלבד." },
        { title: "שמירה", body: "מחברות נשמרות לפי משתמש/ארגון." },
      ],
      openWidget: "notebookLM",
    },
    {
      id: "meckano-attendance",
      categoryId: "meckano",
      title: "מקאנו — נוכחות",
      summary: "דיווח כניסה/יציאה ודוחות (למנויים מורשים).",
      readMinutes: 3,
      steps: [
        { title: "הרשאה", body: "גישה למקאנו לפי מנוי הארגון או משתמש מורשה." },
        { title: "דיווח", body: "פקודות «כניסה למקאנו» / «יציאה ממקאנו» ב-Omnibar או דוחות ייעודיים." },
        { title: "דוחות", body: "יישום «דוחות Meckano» מציג נתוני נוכחות." },
      ],
      openWidget: "meckanoReports",
    },
    {
      id: "settings-org",
      categoryId: "settings",
      title: "הגדרות ארגון",
      summary: "לוגו, מקצוע, Drive ושיוך משתמשים.",
      readMinutes: 4,
      steps: [
        { title: "פתיחה", body: "אייקון גלגל השיניים בתחתית הסרגל." },
        { title: "פרטי ארגון", body: "עדכנו שם, ח.פ, לוגו וסוג עוסק." },
        { title: "Google Drive", body: "הגדרת תיקיית סנכרון וחיבור מחדש." },
        { title: "מנוי", body: "צפו ברמת מנוי ויתרות סריקה (לפי הרשאה)." },
      ],
      openWidget: "settings",
    },
    {
      id: "trouble-oauth",
      categoryId: "troubleshoot",
      title: "בעיות התחברות Google",
      summary: "אין refresh token או חיבור Drive נכשל.",
      readMinutes: 3,
      steps: [
        { title: "התנתקות", body: "צאו מהמערכת והתחברו שוב." },
        { title: "הסכמה מלאה", body: "בהגדרות לחצו «חיבור מחדש ל-Google» — אשרו את כל ההרשאות." },
        { title: "דפדפן", body: "נסו חלון פרטי או דפדפן אחר אם החשבון שמור עם הרשאות ישנות." },
      ],
    },
    {
      id: "trouble-scan",
      categoryId: "troubleshoot",
      title: "סריקה נכשלה",
      summary: "מה לבדוק כשהפענוח לא עובד.",
      readMinutes: 3,
      steps: [
        { title: "גודל וסוג", body: "מקסימום 25MB; ודאו PDF/תמונה ולא קובץ מוצפן." },
        { title: "יתרה", body: "בדקו שנשארו סריקות במנוי (הגדרות / מנהל)." },
        { title: "מנוע", body: "נסו מצב מנוע יחיד או הנחיות סריקה ברורות יותר." },
      ],
      openWidget: "aiScanner",
    },
  ],
  globalFaq: [
    {
      question: "מה ההבדל בין כפתור «עזרה» ל«צ'אט AI»?",
      answer:
        "כפתור העזרה פותח את מרכז העזרה — מדריכים ושאלות נפוצות. צ'אט AI נמצא בסרגל הראשי ומיועד לשאלות חופשיות ופעולות חכמות.",
    },
    {
      question: "איך מאשרים משתמש חדש?",
      answer:
        "מנהל המערכת (בעל הפלטפורמה) נכנס ל«ניהול» → טאב הרשמות → בוחר תוכנית ולוחץ אשר.",
    },
    {
      question: "האם הפריסה נשמרת בין מכשירים?",
      answer: "הפריסה נשמרת ב-localStorage של הדפדפן במכשיר הנוכחי בלבד.",
    },
    {
      question: "איך מוסיפים קובץ מ-Google Drive למחברת?",
      answer: "בווידג'ט Drive לחצו על אייקון המחברת ליד הקובץ או התיקייה.",
    },
    {
      question: "מה עושה Gemini Live?",
      answer:
        "מאפשר שיחה קולית עם העוזר; ניתן לבקש פתיחת מסכים, סריקה, משימות ועוד — לפי הרשאות המנוי.",
    },
    {
      question: "למי מוצג כפתור «ניהול»?",
      answer: "רק למנהל הפלטפורמה (SUPER_ADMIN) — בדרך כלל בעל חשבון BSD-YBM.",
    },
  ],
};
