-- Rename Invoice."payplusTransactionId" -> "gatewayTransactionId".
--
-- The column was never PayPlus-specific in practice: lib/paypal-capture-apply.ts
-- writes PayPal capture ids into it, and the refunds route matches against it for
-- any gateway. With the PayPlus integration removed the name was actively
-- misleading.
--
-- RENAME COLUMN carries the unique index with it, so no index work is needed.
-- Neon has no shadow database, so this migration is hand-written per the
-- convention in CLAUDE.md (gotcha #1) rather than generated by `migrate dev`.
--
-- Deploy note: this is not backward compatible with code that still selects the
-- old name. Ship the migration and the application together (Vercel deploys
-- atomically, so a single deploy is sufficient).

ALTER TABLE "Invoice"
  RENAME COLUMN "payplusTransactionId" TO "gatewayTransactionId";
